#
# Makefile for the RAT project. This requires GNU make on many systems.
#
# $Id: Makefile.in 4427 2009-04-15 21:23:00Z douglask $
#
# Configure substitutes variables here... #####################################

DEFS    = -DHAVE_CONFIG_H -DHIDE_SOURCE_STRINGS
CFLAGS  = -g -O2 -W -Wall -Wbad-function-cast -Wmissing-prototypes $(DEFS)
LIBS    = -ldl  -lieee -lm
LDLIBS  = 
INCLUDE = -I/home/andy/common/src  -I/usr/include/tcl8.5 -I/usr/include/tcl8.5 
CC      = gcc
AR      = ar
RANLIB  = ranlib
ECHO    = echo
STRIP	= strip
INSTALL	= /usr/bin/install -c

VERSION = 4.4.01
RATVER  = rat-$(VERSION)

AUD_OBJ  =  auddev_ixj.o auddev_oss.o
AUD_INC  = 
AUD_LIB  = 

TCL_LIB    = -L/usr/lib -ltcl8.5
TK_LIB     = -L/usr/lib -ltk8.5
X_CFLAGS   =  
X_LIB      = -lX11 -lXss -lXext   
COMMON_LIB = -L/home/andy/common/src -luclmmbase
EXTRA_OBJ  = 
EXTERNAL_DEP = 

G728_CODEC_OBJ = 
G728_LIB       = 

WBS_CODEC_OBJ = codec_wbs.o cx_wbs.o

prefix      = /usr/local
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
bindir      = ${exec_prefix}/bin
mandir      = ${datarootdir}/man
sysconfdir  = ${prefix}/etc

# Nothing below here set by configure #########################################

AUDIO_OBJS   = $(AUD_OBJ) auddev_null.o audio_fmt.o audio_util.o \
               auddev_trans.o auddev.o

CODEC_OBJS   = codec.o codec_state.o codec_dvi.o codec_gsm.o \
               codec_l8.o codec_l16.o codec_g711.o codec_g726.o codec_lpc.o \
               codec_types.o codec_vdvi.o \
               cx_g726.o cx_g726_16.o cx_g726_24.o cx_g726_32.o cx_g726_40.o \
               cx_gsm.o cx_lpc.o cx_vdvi.o cx_dvi.o \
               converter.o convert_util.o convert_extra.o convert_linear.o \
               convert_sinc.o bitstream.o  $(WBS_CODEC_OBJ)

SNDFILE_OBJS = sndfile.o sndfile_au.o sndfile_raw.o sndfile_wav.o

MEDIALIBS    = libuclaudio.a libuclcodec.a libuclsndfile.a 

CHANNEL_OBJS = channel.o channel_types.o cc_vanilla.o cc_rdncy.o cc_layered.o

TOY_OBJS     = render_3D.o repair.o 

MEDIA_OBJS   = ts.o playout.o net.o source.o session.o \
               main_engine.o mbus_engine.o audio.o cushion.o mix.o \
               parameters.o transmit.o playout_calc.o \
               ui_send_rtp.o ui_send_audio.o ui_send_prefs.o ui_send_stats.o \
	       transcoder.o rtp_dump.o rtp_callback.o settings.o \
               pdb.o pktbuf.o tonegen.o voxlet.o fatal_error.o $(EXTRA_OBJ)

UI_OBJS      = tcltk.o mbus_ui.o main_ui.o fatal_error.o

CTRL_OBJS    = main_control.o mbus_control.o codec_compat.o fatal_error.o \
               process.o cmd_parser.o

TCL_OBJS     = ui_audiotool.o ui_transcoder.o 

TCL_SRCS     = $(TCL_OBJS:%.o=%.c)

ALL_OBJS     = $(AUDIO_OBJS) $(CODEC_OBJS) $(SNDFILE_OBJS) $(CHANNEL_OBJS) \
               $(TOY_OBJS) $(MEDIA_OBJS) $(UI_OBJS) $(CTRL_OBJS)

ALL_SRCS     = $(ALL_OBJS:%.o=%.c)

INSTALL_OBJS = ui_installer.o installer.o binaries.o

all: version.h sdr2.plugin.S02.audio.rtp.-.$(RATVER) $(RATVER).spec $(RATVER) $(RATVER)-ui $(RATVER)-media $(RATVER)-kill rat Makefile

libuclaudio.a: $(AUDIO_OBJS)
	$(AR) r $@ $(AUDIO_OBJS)
	$(RANLIB) $@

libuclcodec.a: $(CODEC_OBJS)
	$(AR) r $@ $(CODEC_OBJS)
	$(RANLIB) $@

libuclsndfile.a: $(SNDFILE_OBJS)
	$(AR) r $@ $(SNDFILE_OBJS)
	$(RANLIB) $@

$(RATVER)-kill: rat-kill.o
	$(CC) $(CFLAGS) rat-kill.o $(COMMON_LIB) $(LIBS) -o $(RATVER)-kill

$(RATVER)-media: $(CHANNEL_OBJS) $(TOY_OBJS) $(MEDIA_OBJS) $(MEDIALIBS) $(EXTERNAL_DEP)
	$(CC) $(CFLAGS) $(CHANNEL_OBJS) $(TOY_OBJS) $(MEDIA_OBJS) $(MEDIALIBS) $(COMMON_LIB) $(AUD_LIB) $(LIBS) $(G728_LIB) -o $(RATVER)-media

$(RATVER)-ui: $(TCL_OBJS) $(UI_OBJS) $(EXTERNAL_DEP)
	$(CC) $(CFLAGS) $(TCL_OBJS) $(UI_OBJS) $(COMMON_LIB)  $(TCL_LIB) $(TK_LIB) $(X_LIB) $(LIBS) -o $(RATVER)-ui 

$(RATVER): $(CTRL_OBJS) $(EXTERNAL_DEP)
	$(CC) $(CFLAGS) $(CTRL_OBJS) $(COMMON_LIB) $(LIBS) -o $(RATVER)

.c.o:
	$(CC) $(CFLAGS) $(X_CFLAGS) $(INCLUDE) -c $<

$(TCL_OBJS): $(TCL_SRCS)

ui_transcoder.c: ui_transcoder.tcl tcl2c/tcl2c
	cat ui_transcoder.tcl | tcl2c/tcl2c ui_transcoder > ui_transcoder.c

ui_audiotool.c: uicomponent_bargraph.tcl uicomponent_chart.tcl uicomponent_help.tcl asfilebox.tcl ui_audiotool.tcl tcl2c/tcl2c
	cat uicomponent_bargraph.tcl uicomponent_chart.tcl uicomponent_help.tcl asfilebox.tcl ui_audiotool.tcl | tcl2c/tcl2c ui_audiotool > ui_audiotool.c

ui_installer.c: ui_installer.tcl tcl2c/tcl2c
	cat ui_installer.tcl | tcl2c/tcl2c ui_installer > ui_installer.c

tcl2c/tcl2c: tcl2c/tcl2c.c
	$(CC) -o tcl2c/tcl2c tcl2c/tcl2c.c

version.h: VERSION
	@${ECHO} "Generating version.h"
	@sed -e 's/.*/#define RAT_VERSION "&"/' VERSION > version.h

sdr2.plugin.S02.audio.rtp.-.rat-$(VERSION): sdr2.plugin.in
	@${ECHO} "Generating sdr plugin"
	@${ECHO} "# Generated automatically from sdr2.plugin.in" > $@
	@${ECHO} "# DO NOT EDIT THIS FILE" >> $@
	@sed -e 's/VERSION/$(VERSION)/g' sdr2.plugin.in >> $@

rat-$(VERSION).spec: rat.spec
	@${ECHO} "Generating RPM spec file"
	@${ECHO} "# Generated automatically from rat.spec"  > $@
	@${ECHO} "# DO NOT EDIT THIS FILE"                 >> $@
	@cat rat.spec | sed s/VERSION/$(VERSION)/g       >> $@

rat: VERSION Makefile
	@${ECHO} "Generating rat shell script"
	@${ECHO} "#!/bin/sh" > $@
	@${ECHO} "# Generated automatically from RAT Makefile.  Edit there." >> $@
	@${ECHO} 'PATH=$${PATH}:.' >> $@
	@${ECHO} "exec rat-$(VERSION)" \"'$$@'\" >> $@
	@chmod a+x rat

clean:
	-rm -f $(CTRL_OBJS) $(AUDIO_OBJS) $(CODEC_OBJS) $(SNDFILE_OBJS) $(CHANNEL_OBJS) $(TOY_OBJS) $(MEDIA_OBJS) $(UI_OBJS) $(TCL_OBJS)
	-rm -f $(MEDIALIBS)
	-rm -f rat-kill.o
	-rm -f tcl_libs.c ui_audiotool.c ui_transcoder.c ui_installer.c version.h
	-rm -f tcl2c/tcl2c sdr2.plugin.S02.audio.rtp.-.$(RATVER) $(RATVER).spec
	-rm -f bin2c bin2c.o binaries.c rat-kill.o $(INSTALL_OBJS) $(RATVER)-installer
	-rm -f rat $(RATVER)-media $(RATVER)-ui $(RATVER)-kill $(RATVER)

distclean: clean
	-rm -rf autom4te.cache config.cache config.log config.status
	-rm -rf ratconf.h Makefile
	-rm -rf core core-$(RATVER)-media core-$(RATVER)-ui

install: all
	test -d $(DESTDIR)$(bindir) || \
		$(INSTALL) -d $(DESTDIR)$(bindir)
	test -d $(DESTDIR)$(mandir)/man1 || \
		$(INSTALL) -d $(DESTDIR)$(mandir)/man1
	test -d $(DESTDIR)$(sysconfdir)/sdr/plugins || \
		$(INSTALL) -d $(DESTDIR)$(sysconfdir)/sdr/plugins
	$(INSTALL) -m 555 -c rat             $(DESTDIR)$(bindir)
	$(INSTALL) -m 555 -c $(RATVER)       $(DESTDIR)$(bindir)
	$(INSTALL) -m 555 -c $(RATVER)-kill  $(DESTDIR)$(bindir)/rat-kill
	$(INSTALL) -m 555 -c $(RATVER)-media $(DESTDIR)$(bindir)
	$(INSTALL) -m 555 -c $(RATVER)-ui    $(DESTDIR)$(bindir)
	$(INSTALL) -m 444 -c man/man1/rat.1  $(DESTDIR)$(mandir)/man1/rat.1
	$(INSTALL) -m 444 -c sdr2.plugin.S02.audio.rtp.-.$(RATVER) $(DESTDIR)$(sysconfdir)/sdr/plugins

installer: $(RATVER)-installer
	mkdir release
	mkdir release/$(RATVER)
	cp $(RATVER)-installer README.* MODS COPYRIGHT INSTALL.TXT VERSION release/$(RATVER)
	cd release && tar cvf $(RATVER)-$(OSTYPE).tar $(RATVER) && gzip -9 $(RATVER)-$(OSTYPE).tar
	mv release/$(RATVER)-$(OSTYPE).tar.gz .
	rm -rf release

$(RATVER)-installer: $(INSTALL_OBJS)
	$(CC) $(CFLAGS) $(INSTALL_OBJS)  $(TCL_LIB) $(TK_LIB) $(X_LIB) $(LIBS) -o $(RATVER)-installer

binaries.c: $(RATVER)-$(OSTYPE).tar.gz bin2c
	./bin2c $(RATVER)-$(OSTYPE).tar.gz > binaries.c

bin2c: bin2c.o
	$(CC) bin2c.o -o bin2c

etags:
	etags ../common/src/*.[ch] *.[ch]

ctags:
	ctags ../common/src/*.[ch] *.[ch] 

release:
	cvs tag release-`cat VERSION | sed "s/\./-/g"`

$(RATVER)-$(OSTYPE).tar.gz: $(RATVER) $(RATVER)-ui $(RATVER)-media rat
	tar cf $(RATVER)-$(OSTYPE).tar README.* MODS COPYRIGHT INSTALL.TXT VERSION $(RATVER) $(RATVER)-ui $(RATVER)-media sdr2.plugin.S02.audio.rtp.-.rat-$(VERSION) rat
	rm -f $(RATVER)-$(OSTYPE).tar.gz
	gzip -9 $(RATVER)-$(OSTYPE).tar

tgz: $(RATVER)-$(OSTYPE).tar.gz

rpm: clean tgz 
	@${ECHO} "Building $(RATVER).rpm -- this almost certainly needs to run as root on RedHat Linux"
	install -m 644 $(RATVER)-$(OSTYPE).tar.gz /usr/src/redhat/SOURCES/$(RATVER)-$(OSTYPE).tar.gz
	rpm -bb $(RATVER).spec

Makefile: Makefile.in VERSION
	$(error "Run configure again, the following file(s) are newer than Makefile: $?")

depend:
	makedepend $(X_CFLAGS) $(INCLUDE) $(ALL_SRCS)
# DO NOT DELETE THIS LINE
